version: 1.0.{build}
os: Visual Studio 2015

configuration: Release

shallow_clone: true

before_build:
- cmd: cd PreMailer.Net
- cmd: dotnet restore

build_script:
- cmd: dotnet build PreMailer.Net.Core -c Release

test: off
test_script:
- cmd: dotnet test PreMailer.Net.Core.Tests

artifacts:
- path: '*.nupkg'
  name: PreMailer.nupkg

before_deploy:
- cmd: dotnet pack PreMailer.Net.Core -c Release

deploy:
- provider: NuGet
  api_key:
    secure: SkGbCeLcNMjPh6nghMU4johO4Nfhz/HhVjDfAybWV6kImAKwwT7iQXzh98ksnqcS
  artifact: PreMailer.nupkg
  on:
    APPVEYOR_REPO_TAG: true

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  auth_token:
    secure: gZ2OpPFLjVnhnhvUdG4JZw==
  channel: general
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

init:
- appveyor version
- cmd: echo %APPVEYOR_REPO_TAG%
- cmd: IF %APPVEYOR_REPO_TAG%==true echo %APPVEYOR_REPO_TAG_NAME%
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
